// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVmO1JRU552L2OhuDi0sdRhwgleBPNO3c',
    appId: '1:81093612277:web:2701028bba2df35b4febbc',
    messagingSenderId: '81093612277',
    projectId: 'allnimall',
    authDomain: 'pet-allnimall.web.app',
    storageBucket: 'allnimall.appspot.com',
    measurementId: 'G-XB39WBWL38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBydXSoppRjB-gdhCkIckjS0O_t9hzMgtw',
    appId: '1:81093612277:android:8bcb0ab1555217b14febbc',
    messagingSenderId: '81093612277',
    projectId: 'allnimall',
    storageBucket: 'allnimall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX9Kl_giqmL8K8JGZlFN6RaPLxq6g6Xp0',
    appId: '1:81093612277:ios:b0e581352d9cf6224febbc',
    messagingSenderId: '81093612277',
    projectId: 'allnimall',
    storageBucket: 'allnimall.appspot.com',
    androidClientId:
        '81093612277-0otsrj7rfnrur46jt8s74n6qflnq1ncl.apps.googleusercontent.com',
    iosClientId:
        '81093612277-g22qohp8q6es40d1tmanjuq4vm4svjgm.apps.googleusercontent.com',
    iosBundleId: 'com.allnimall.app.allnimallQr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX9Kl_giqmL8K8JGZlFN6RaPLxq6g6Xp0',
    appId: '1:81093612277:ios:b0e581352d9cf6224febbc',
    messagingSenderId: '81093612277',
    projectId: 'allnimall',
    storageBucket: 'allnimall.appspot.com',
    androidClientId:
        '81093612277-0otsrj7rfnrur46jt8s74n6qflnq1ncl.apps.googleusercontent.com',
    iosClientId:
        '81093612277-g22qohp8q6es40d1tmanjuq4vm4svjgm.apps.googleusercontent.com',
    iosBundleId: 'com.allnimall.app.allnimallQr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKL4836fuagZwBfUzvqeDpjJYEz94xFMM',
    appId: '1:81093612277:web:c71b4b72772731aa4febbc',
    messagingSenderId: '81093612277',
    projectId: 'allnimall',
    authDomain: 'allnimall.firebaseapp.com',
    storageBucket: 'allnimall.appspot.com',
    measurementId: 'G-G4W2RL1E50',
  );
}
